apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  namespace: operators
  labels:
    example: basic
    test: label
spec: 
  redis:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi


