apiVersion: v1
kind: Secret
metadata:
  name: cluster-test
  namespace: operators
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster-test
  server: https://127.0.0.1:41229
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
