apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projet-test
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: tester un projet dans argocd 
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to namespaces in defined clusters
  destinations:
  # - name: '!in-cluster'
  - namespace: '*'
    server: '*'
